### PR TITLE
chore: Add ESLint

### PR DESCRIPTION
**Pull request by Areadrill**

### CODE REVIEW

**Comment by Areadrill** [comment]
Will fix in a bit

**Comment by Areadrill** [comment]
Apologies, ended up having quite chaotic work days. Will try to fix during the weekend

**Comment by Areadrill** [comment]
Ended up doing it quickly. Apologies for delay and confusion.

**Review by lmcjt37 — APPROVED** [review]
Great work!

**Comment by lmcjt37** [comment]
@Areadrill Going to merge this by bypassing branch protection. 

But for the future you should create a feature branch to merge into `main` rather than making changes on `main` directly.

**Comment by Areadrill** [comment]
Will do, sorry for the hassle

**Comment by lmcjt37** [comment]
@Areadrill 
> Will do, sorry for the hassle

Don't apologise, thanks for being involved 🙏

**Pull request merged**
